### ISSUE TITLE
Precompiled

### ISSUE THREAD

**Issue by BHare1985** [gaspardle/mapnik-mssql#1]
Any chance you could please compile this for 64 bit windows? 

I am restricted from compiling things but would like to use this plugin.

Thanks

**Comment by gaspardle** [comment]
Hi, I do have a compiled version here: https://github.com/gaspardle/mapnik-mssql/releases. It was compiled with VS2015 CTP6. I'll try later to put new one made with VS2015 RC and a newer mapnik sdk.

**Comment by BHare1985** [comment]
Thanks, sorry I normally dont check out the releases of GitHub. My mistake :)

**Comment by gaspardle** [comment]
https://github.com/gaspardle/mapnik-mssql/releases/tag/v0.1.1-alpha
