### ISSUE TITLE
Trace flag 4199 and filter vs intersects

### ISSUE THREAD

**Issue by BHare1985** [gaspardle/mapnik-mssql#11]
Sql Server can be really dumb about when to use spatial indices. Enabling `OPTION(QUERYTRACEON 4199)` seems to help a lot but AFAIK it has to be appended at the end of a query.
Enabling the trace flag 4199 globally can has negative effects so it would be great if there was an option for us to have it be sent with the query/session that mapnik is using so we can get the benefits without running the risk enabling the flag outside mapnik.

Also, this is a minor thing but according to http://social.technet.microsoft.com/wiki/contents/articles/9694.tuning-spatial-point-data-queries-in-sql-server-2012.aspx it seems that `filter` can be much quicker than `STIntersects`, but it has some false positives so it would be neat if there was an option to use `filter` at a certain zooms and then once it reaches a point where accuracy matters much more switch to `STIntersects`

**Comment by gaspardle** [comment]
I just tried it and it was really faster on some queries. I'Il do some more benchmarking and see how we can add theses options.

One issue I see for `OPTION(QUERYTRACEON 4199)` is that the user needs to be in the sysadmin group to set this option. or we get the error  `User 'osmtest' does not have permission to run DBCC TRACEON.`

For `Filter`, I don't think false positives and having features outside the bounding box matters, mapnik should ignore them, but i'll have to check.

**Comment by gaspardle** [comment]
I added these two options: `use_filter` and `trace_flag_4199`. They are disabled by default.

**Comment by BHare1985** [comment]
So far I have tested it on windows and have verified both flags work. 

I have yet to compile on amazon linux to see if that works, but suspect no issues. Will report back on that when I have tested it.

---

I haven't tested much if filter has negative effects for false positives. This wouldn't be an issue with point data as mapnik cuts at the boundaries of the tile but my concern was polyline data where a line can span multiple tiles and perhaps how metatiles may play a role in that.

---

In regards to sysadmin group one alternative is to execute a stored procedure instead of doing a parameterless query.

This actually now has four benefits;

A) Sql server no longer has to regenerate a plan and do all the work needed for each and every tile so will be sped up (See http://stackoverflow.com/questions/8559443/why-execute-stored-procedures-is-faster-than-sql-query-from-a-script)
B) It gets around the permission issue for DBCC TRACEON
C) It allows the end user much greater control over the query, allowing them to add any flag they want and control incoming bounding boxes and inputs.
D) It has the benefits of security checking for datatypes and preventing SQL injection

D has been a small concern of mine because I am using a tile server that is an early derivation of cartodb, which means I take in custom queries, and sometimes user-input queries.

Seems passing in the bounding box as a geometry to a stored procedure would be ideal for this plugin and mapnik/sqlserver integration. Implementation could get complicated if you were wanting to also pass in the each field the user wanted its real datatype, but a prototype could start with just a string of the original sql/table (the plugins table parameter) and get in an geometry input that is the bounding box.

**Comment by BHare1985** [comment]
As for the stored procedure idea, one of your forks did just that https://github.com/jc101/mapnik-mssqlsp  (wasn't able to contact him to see if he got it working).

I am closing this because the two suggested feature requests have been implemented
