### ISSUE TITLE
Fetch the geometry column as a WKB

### ISSUE THREAD

**Issue by BHare1985** [gaspardle/mapnik-mssql#13]
for the wkb parameter: 

> Fetch the geometry column as a WKB with .STAsBinary() instead of using SQL Server CLR type.

What exactly is the benefit of using WKB over CLR? I googled it and couldn't come up with any definitive answer so I was curious what you added this feature. Is it because using WKB may take up less CPU but maybe a more network time?

**Comment by gaspardle** [comment]
There's no benefits. Using wkb will use more cpu cycles on the database server. Early versions of the plugin used wkb, the code to parse the native sql server format was added later.
