### ISSUE TITLE
v0.2.168 SQLAllocHandle 

### ISSUE THREAD

**Issue by BHare1985** [gaspardle/mapnik-mssql#17]
I am getting `Mssql Plugin: SQLAllocHandle SQL_HANDLE_DBC failed` randomly zoom and pan on the map. Sql server 2014 enterprise 12.0.4100.1, running plugin and sql server both on windows 10. I made sure to get the x64 version.

Seems to happen intermittently, after browsing around for 2-3 minutes. Before that things seem OK

Here is a video showcasing it with my nodejs request logging (bottom right) map (left) and sql profiler (top right). Happens around 1:30 mark: https://dl.dropboxusercontent.com/u/8518063/ShareX/2016/06/2016-06-19_21-37-24.mp4

Its worth noting one time it did this I got up from my desk came back and it fixed itself, seemingly related to logging in and out? not sure.

**Comment by gaspardle** [comment]
Ok I have removed the release. I'll do more debug this week.

**Comment by gaspardle** [comment]
Hi, I have put a 0.1 version but linked with mapnik 3.0.11 
https://github.com/gaspardle/mapnik-mssql/releases/tag/v0.1.169

And a 0.2 that will output a little more debug information, if you could run it, it would help. I could not reproduce the bug, but i think i know what is causing this.
https://ci.appveyor.com/project/gaspardle/mapnik-mssql/build/v0.2.170-issue17/job/50mhp8ns725ighip/artifacts

**Comment by BHare1985** [comment]
0.2 produced this

```
mssql Plugin: SQLAllocHandle SQL_HANDLE_DBC  returncode: -2, envhandle: 0000000000000000
Trace: [Error: mssql Plugin: SQLAllocHandle SQL_HANDLE_DBC  returncode: -2, envhandle: 0000000000000000]
```

**Comment by gaspardle** [comment]
Try this one, if it work, i'll do a definitive fix this week, or next weekend.

https://ci.appveyor.com/project/gaspardle/mapnik-mssql/build/v0.2.171-issue17/job/7vk3mfrc6ve4a9qd/artifacts

**Comment by BHare1985** [comment]
Seems to have fixed it, I was unable to get it to error out

**Comment by BHare1985** [comment]
I just got this error again on linux when i built from source, was v0.2.171 not updated in the code?

I think only branch `issue17` has the fix. I think its ok to go ahead and include it in master

**Comment by gaspardle** [comment]
It is now in master.
