### ISSUE TITLE
Possible extent error

### ISSUE THREAD

**Issue by BHare1985** [gaspardle/mapnik-mssql#4]
I notice you do 

```
SELECT ext.STPointN(1).STX AS MinX, ext.STPointN(1).STY AS MinY,ext.STPointN(3).STX AS MaxX, ext.STPointN(3).STY AS MaxX FROM (SELECT geometry::EnvelopeAggregate(Shape) as ext from FLORIDA) as tmp
```

and the like to try to find max extent. I know I can set this manually to avoid these calls but I noticed you are defining MaxY as MaxX twice, possible running into an error in your backend.

**Comment by gaspardle** [comment]
Thanks, it's now corrected. It should not have caused any problems because we get the data from the number of the column, not it's name.
