### ISSUE TITLE
Incorrect STEnvelope ?

### ISSUE THREAD

**Issue by BHare1985** [gaspardle/mapnik-mssql#5]
I have a tile that takes about 6 seconds for mssql using your plugin to run. However,  if I define a polygon bounding box and run intersect around it manually it goes down to 2 seconds.

the SQL thats ran via your plugin:

``` sql
SELECT "Shape" AS geom FROM FLORIDA WHERE "Shape".STIntersects(geometry::STLineFromText('LINESTRING(-82.44140625000001 28.14950321154457,-81.38671875 29.07537517955835)', 4326).STEnvelope()) = 1
```

Here is the extent mapped out  : http://i.imgur.com/7woMf9b.png

I used this tool for mapping the LINESTRING: http://arthur-e.github.io/Wicket/sandbox-gmaps3.html

The red line is your LINESTRING, the blue box is the envelope it will make, and the green box is the actual tile.

is this expected behavior? Seems like the blue box should be the size of the green box.

Do you make find the LINESTRING of the envelope yourself or is it passed it by mapnik? I am using the mapnik VS2015 RC SDK and my windows/mssql-tweaked windshaft: https://github.com/BHare1985/Windshaft

**Comment by gaspardle** [comment]
The bounding box is directly passed from mapnik. 
I see that you're using 4326 srid, try the latest version, it should correcly detect the srid instead of assuming it's in 3857. I don't think this is what is causing this issue, but i'll check later with a table with 4236 geometries.

**Comment by BHare1985** [comment]
No difference with 0.1.18. 

Still get `SELECT "Shape" AS geom FROM FLORIDA WHERE "Shape".STIntersects(geometry::STLineFromText('LINESTRING(-82.44140625000001 28.14950321154457,-81.38671875 29.07537517955835)', 4326).STEnvelope()) = 1`

**Comment by BHare1985** [comment]
It's worth noting that after installing the server seems to freeze at times during startup.

**Comment by gaspardle** [comment]
Can you send me the coordinates of the tile ?

**Comment by BHare1985** [comment]
zxy : 10 279 426

**Comment by BHare1985** [comment]
Accoridng to http://www.maptiler.org/google-maps-coordinates-tile-bounds-projection/
The bounds are

== Tile Boundaries ==
WGS84 datum (longitude/latitude):
-81.9140625    28.613459424004414
-81.5625     28.92163128242129

**Comment by BHare1985** [comment]
it looks like your midpoint is actually the bottom left starting point of the bounds.

**Comment by gaspardle** [comment]
I tried to directly render the same tile with the above bounding box , 

```
Map m(256, 256);
load_map(m, "Imposm3test\\Imposm3test-fl-4326.xml", false, "Imposm3test\\");
m.zoom_to_box(box2d<double>(-81.9140625, 28.613459424004414, -81.5625, 28.92163128242129));
mapnik::image_rgba8 buf(m.width(), m.height());
agg_renderer<image_rgba8> ren(m, buf);
ren.apply();
save_to_file(buf, "test-4236.png", "png");
```

but it gives me this linestring in the query 
`LINESTRING(-81.9140625 28.59176410321285,-81.5625 28.94332660321285)`

We don't do any manipulation of the box given by mapnik. It use the same code as the postgis datasource. If you use the postgis plugin, does it do a different bounding box ?

I didnt try it with the windshaft server, i cant get it to install.

Also I changed the linestring/STEnvelope for a polygon.

**Comment by BHare1985** [comment]
I saw the polygon change. Seems to be a bit slower as far as I can tell but not by much...Would need to really stress test it to see if not just random chance that I saw a difference. Contained 200,000 polylines.

I ran it with postgres/postgis with different data (cant import my data to postgis) but same coords and the plugin gave:

`
SELECT ST_AsBinary("the_geom_webmercator") AS geom FROM test_table WHERE "the_geom_webmercator" && ST_SetSRID('BOX3D(-82.43983718478415 28.14822600194032,-81.38518385863568 29.07409738219564)'::box3d, 4623)
`

Which is the same bounding box, so it seems not an issue on your plugin.

**Comment by BHare1985** [comment]
I turned metatile to be 1.. I wasn't passing any parameters to mapnik and it did:

`SELECT "Shape" AS geom FROM FLORIDA WHERE "Shape".STIntersects(geometry::STLineFromText('LINESTRING(-82.00195312500001 28.53627451298992,-81.474609375 28.99853181405179)', 4326).STEnvelope()) = 1`

Which is correct now. So that is what it was, I guess they use the cached results of a db call to get 4 tiles at a time.

Edit: I was using SRID 4623 and not 4326 for postgis... with 4326 it does

`
SELECT ST_AsBinary("the_geom_webmercator") AS geom FROM test_table WHERE "the_geom_webmercator" && ST_SetSRID('BOX3D(-82.00195312500001 28.53627451298992,-81.474609375 28.99853181405179)'::box3d, 4326)
`
