### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by jbrwn** [gaspardle/mapnik-mssql#6]
Hey nice work on this repo.  I'd love to start contributing.   Is there anything i should know about contributing before i start submitting pull requests?  

Here are some areas i'd like to work on:
- Add tests
- Support more mssql datatypes (date/time, etc..)
- Add continous integration (Appveyor)
- benchmark tests (e.g. vs OGR plugin, vs PostGIS plugin)

Let me know what you think.

**Comment by gaspardle** [comment]
That would be great, anything you can help with will be appreciated.

It was based on the postgis plugin, so there may still be some postgres specific things.

I started working on a version that work directly with freetds without odbc, but i'm not sure if there's enough advantage. I'll try to create a branch with it later.

I'll put the current appveyor config in the repo.

**Comment by jbrwn** [comment]
Right on.  

What is your thinking on using the freetds lib directly?  Does it offer a noticeable performance improvement over ODBC?  It looks like the freetds project is pretty active but i'm a little hesitant on first reaction locking into a single driver implementation and throwing away the ODBC/sql native client option.  just my 2 cents.

**Comment by gaspardle** [comment]
I did not test it extensively but it was not really faster.

The only advantage i see for using freetds directly is easier configuration, because we don't need odbc or the odbc driver installed, and no driver name to specify.

**Comment by jbrwn** [comment]
Closing this issue.  I'm interested in the freetds approach but we can move that to another issue if need be.  Thanks!
