### ISSUE TITLE
(dlopen failed - plugin likely has an unsatisfied dependency or incompatible ABI)

### ISSUE THREAD

**Issue by BHare1985** [gaspardle/mapnik-mssql#9]
Been a while since I used Mapnik. I am using node-mapnik 3.4.5, which I think doesn't actually have mapnik 3.0 binaries (not 100% sure). 

When trying to run my version of node-mapnik with this plugin using version v0.1.43 it says 
(dlopen failed - plugin likely has an unsatisfied dependency or incompatible ABI)

Tried all 4 versions with no luck.

I assume Mapnik 3.0 is a hard dependency now for newer releases, but can you enable the release downloads for when it wasn't required? I have v0.1.5 alpha but would be nice to have access later on to any version.

**Comment by gaspardle** [comment]
Which version of node are you using?

On Wed, Sep 9, 2015 at 1:52 PM, Brian Hare notifications@github.com wrote:

> Been a while since I used Mapnik. I am using node-mapnik 3.4.5, which I
> think doesn't actually have mapnik 3.0 binaries (not 100% sure).
> 
> When trying to run my version of node-mapnik with this plugin using
> version v0.1.43 it says
> (dlopen failed - plugin likely has an unsatisfied dependency or
> incompatible ABI)
> 
> Tried all 4 versions with no luck.
> 
> I assume Mapnik 3.0 is a hard dependency now for newer releases, but can
> you enable the release downloads for when it wasn't required? I have v0.1.5
> alpha but would be nice to have access later on to any version.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gaspardle/mapnik-mssql/issues/9.

## 

_Luc-Edmond Gaspard_

**Comment by BHare1985** [comment]
Node 0.12.3

**Comment by gaspardle** [comment]
node-mapnik 3.4.5 does come with mapnik 3.0. 

Try the 0.1.48 release that is built against mapnik 3.0.4, I just tested it with node 0.12.7.

**Comment by BHare1985** [comment]
It works. Thanks a lot

**Comment by BHare1985** [comment]
I am getting this same error again but this time on Amazon Linux. I am attempting to get this to work on Beanstalk using node 12.6.  I assume I'll need the visual studio 2015 dependency for the amazon linux, any idea where to get that?

Rather what dependencies does the compiled input file need (and where to download / yum them) for Amazon Linux?

**Comment by BHare1985** [comment]
I ended up compiling the plugin with Amazon Linux (of which unixODBC-devel is a dependency that wasn't obvious) using Mapnik 3.0.4 SDK ( http://mapnik.s3.amazonaws.com/dist/dev/mapnik-linux-sdk-v3.0.4.tar.bz2 )

And I am still getting the same error, but to be fair my compiled mssql.input is 219kb vs your 175kb and   doesnt even work for Windows either, get the same error. I probably compiled it wrong but I saw no errors.

**Comment by BHare1985** [comment]
I think I managed some progress, I thought unixODBC was just a compiling dependency, I had to install unixODBC on the Amazon Linux AMI as well, now I am just wrestling with `Mssql Plugin: (1) SQLState: IM002 NativeError: 0 Message: [unixODBC][Driver Manager]Data source name not found, and no default driver specified MsgLen: 85 SQLDriverConnect Error, Connection string: 'DRIVER={SQL Server Native Client 11.0};SERVER=8.43.17.158/ALIENWARE;DATABASE=TTD;UID=ttd;connect_timeout=4;' encountered during parsing of layer 'MAPNIK' in Layer`

Which I think is just an ODBC driver configuration I have to sort out, unless the connection string needs changed to be a different driver?

**Comment by BHare1985** [comment]
Closing this, as the original problem was solved now its about ODBC and FreeTDS
